export const SHELL_COPY = {
  brand: {
    ngumpulyukDesc: 'Tempat ngumpul yang actually fun',
    ngumpskyDesc: 'Bestie buat cari vibe ngumpul',
  },
  sidebar: {
    quickSection: 'Gas dulu',
    navSection: 'Jelajah',
    activityTitle: 'Ringkasan kamu',
    eventFollowed: 'Event diikuti',
    communities: 'Komunitas',
  },
  nav: {
    chat: 'Chat',
    explore: 'Explore',
    community: 'Komunitas',
    map: 'Peta',
    profile: 'Profil',
  },
  chat: {
    inputPlaceholder: 'Spill aja, event, komunitas, atau yang lagi rame…',
    welcomeWithReco: (name) =>
      `Hai ${name}! Gue Ngumpsky, bestie ngumpul kamu. Nih rekomendasi yang vibes-nya cocok:`,
    welcomeNoReco: (name) =>
      `Hai ${name}! Gue Ngumpsky, siap bantu cari event kece, komunitas, atau spot yang lagi rame. Ketik aja.`,
    recoLoading: 'Lagi scan event yang cocok buat kamu…',
    createEvent: 'Buat Event',
    createEventShort: 'Buat',
  },
  pages: {
    exploreTitle: 'Explore',
    exploreSubtitle: 'Yang mau datang & yang udah lewat',
    exploreUpcoming: 'Mau datang',
    explorePast: 'Udah lewat',
    exploreUpcomingEmpty: 'Belum ada agenda. Yuk jadi yang pertama ngadain!',
    exploreUpcomingEmptyFiltered: 'Gak nemu yang pas. Coba ganti filter ya.',
    explorePastEmpty: 'Belum ada event yang udah lewat.',
    mapTitle: 'Peta Event',
    mapSubtitle: 'Cuma event yang belum lewat, biar gak FOMO ke yang udah done',
    communityTitle: 'Komunitas',
    communitySubtitle: 'Ngobrol, connect, dan gas bareng circle kamu',
    createCommunity: 'Buat Komunitas',
    createCommunityShort: 'Buat',
    createEventTitle: 'Buat Event',
    createEventSubtitle: 'Ramein acara kamu, ajak circle ikutan',
    editEventTitle: 'Edit Event',
    editEventSubtitle: 'Update detail biar makin kece',
    createCommunityTitle: 'Buat Komunitas',
    createCommunitySubtitle: 'Bikin circle sendiri, ajak yang vibes-nya sama',
    notificationsTitle: 'Notifikasi',
    notificationsSubtitleUnread: (unread, total) =>
      `${unread} belum kebaca${total > 0 ? `, ${total} total` : ''}`,
    notificationsSubtitleAllRead: (total) =>
      `Semua udah kebaca${total > 0 ? `, ${total} total` : ''}`,
    notificationsBlastTitle: 'Blast Notifikasi',
    notificationsBlastSubtitle: 'Kirim hype ke circle kamu sekaligus',
    profileLoadingTitle: 'Sabar ya...',
    profileLoadingSubtitle: 'Lagi tarik data profil',
    profileMyTitle: 'Profil kamu',
    profileNotFound: 'Profil gak ketemu',
    profileUpcomingEvents: 'Event akan datang',
    profileEventHistory: 'Riwayat event diikuti',
    profileMyCircles: 'Circle kamu',
    profileSeeAllCircles: 'Lihat semua circle',
    profileNoCircles: 'Belum join circle.',
    profileOpenEvent: 'Buka detail event',
    profileOpenCircle: 'Buka detail circle',
    threadTitle: 'Thread',
    threadSubtitle: 'Diskusi panas dari komunitas',
    communityEmptyTitle: 'Belum ada komunitas',
    communityEmptyNoSearch:
      'Yuk bikin circle pertama, spill vibes kamu ke sini',
    communityEmptySearch: 'Gak ketemu, coba kata kunci lain ya',
    communityHubHint:
      'Spill di obrolan atau join circle baru. Circle kamu ada di tab Circle.',
    communityJoinedEmpty:
      'Kamu belum join circle. Pilih "Explore circle" di bawah atau buat circle sendiri.',
    communityTabFeed: 'Obrolan',
    communityTabCircles: 'Circle',
    communityFeedTitle: 'Update circle',
    communityFeedEmpty: 'Feed masih sepi. Jadi yang pertama spill!',
    communitySearchPlaceholder: 'Cari circle kamu…',
    communityJoinedSection: 'Circle kamu',
    communityExploreSection: 'Explore circle',
    communityDetailBack: 'Kembali',
    communityDetailMembers: (n) => `${n} anggota`,
    communityDetailJoin: 'Gabung',
    communityDetailLeave: 'Keluar',
    communityDetailDelete: 'Hapus circle',
    communityDetailOwnerLeaveHint:
      'Sebagai pembuat circle, kamu tidak bisa sekadar keluar. Hapus circle untuk menutup komunitas ini.',
    communityDetailThreads: 'Diskusi',
    communityDetailThreadsEmpty: 'Belum ada diskusi.',
    communityDetailThreadsEmptyJoined: 'Belum ada diskusi. Spill duluan!',
    communityDetailThreadsEmptyGuest: 'Gabung dulu biar bisa spill di sini.',
    mapEventsFound: (n) => `${n} event akan datang`,
    mapEventsFoundDistance: ', diurutkan dari yang deket',
    communityAllJoinedHint:
      'Semua circle di halaman ini udah kamu join. Cek bagian atas.',
    communityFeedEventHint: (n) =>
      `${n} event kamu akan datang. Bisa di-link pas spill.`,
  },
  threadComposer: {
    expandPrompt: 'Spill apa yang lagi kamu pikirin…',
    placeholder: 'Spill apa yang lagi kamu pikirin…',
    placeholderCommunity: (name) => `Spill di ${name}…`,
    postButton: 'Spill',
    photo: 'Foto',
    photoCount: (n, max) => `${n}/${max}`,
    postingIn: (name) => `Posting di ${name}`,
    selectedCircle: (name) => `Circle: ${name}`,
    feedHint: 'Tanpa pilih circle, spill masuk feed umum',
    addCircle: 'Pilih circle',
    addEvent: 'Link event',
    circleLabel: 'Post di circle',
    circleFeed: 'Feed umum',
    circleNone: 'Belum join circle. Spill ke feed umum dulu.',
    eventLabel: 'Tautkan event (opsional)',
    eventNone: 'Tanpa event',
    imageError: 'Maks 3 foto, PNG/JPG/WEBP, max 3MB',
    circleSearchPlaceholder: 'Ketik nama circle…',
    eventSearchPlaceholder: 'Ketik nama event…',
    circleManyHint: (n) => `${n} circle kamu. Ketik buat nyaring.`,
    eventManyHint: (n) => `${n} event kamu. Ketik buat nyaring.`,
    circleNotFound: 'Gak ketemu circle-nya',
    eventNotFound: 'Gak ketemu event-nya',
    pickCircle: 'Pilih circle',
    pickEvent: 'Link event',
    eventEmptyTitle: 'Belum ada event buat di-link',
    eventEmptyHint:
      'Join event di Explore dulu, nanti bisa ditautkan ke spill kamu',
    eventExploreCta: 'Cari event',
    upcomingEventsOnCard: (n) =>
      n === 0 ? 'Belum ada event akan datang' : `${n} event akan datang`,
    myUpcomingEvents: (n) => `${n} event kamu akan datang`,
  },
  sidebarActions: {
    findEvent: 'Cari Event',
    sports: 'Olahraga',
    sportsPrompt: 'Ada event olahraga minggu ini yang worth it?',
    weekend: 'Weekend',
    weekendPrompt: 'Event seru buat weekend ini, spill rekomendasinya dong',
    community: 'Komunitas',
    communityPrompt: 'Komunitas apa yang cocok buat aku join?',
  },
  welcomeChips: [
    'Olahraga minggu ini',
    'Event weekend dong',
    'Komunitas yang aktif',
    'Ada yang deket aku?',
  ],
};
